modulo-3/sources/my_first_app/config/routes.rb
MyFirstApp::Application.routes.draw do
  get "recipes/search"
  get "translators/translate"
  get "translators/detect"
  get "translators/languages"

  get 'greeter/hello' => "greeter#hello"
  get 'greeter/goodbye'

  root "translators#languages"

end

modulo-3/sources/my_first_app/app/models/google_translate.rb
class GoogleTranslate
  include HTTParty
  default_options.update(verify: false)
  base_uri "https://www.googleapis.com/language/translate/v2"
  format :json

  @@api_key = "AIzaSyBdqiJZunlGxiU5ubdmKlp2VqxqR7GYLsQ"

  default_params key: @@api_key

  attr_accessor :source, :target, :text

  def initialize(source, target)
    @source = source
    @target = target
  end

  def translate(search)
    options = { query: {q: search, source:@source, target:@target}}
    response = self.class.get("", options)
    if response.success?
      response
    else
      raise response.response
    end
  end

  def self.detect(target_language)
    options = { query: {q: target_language}}
    response = get("/detect", options)
    if response.success?
      response
    else
      raise response.response
    end
  end

  def self.languages(target)
    options = { query: {target: target}}
    response = get("/languages", options)
    if response.success?
      response
    else
      raise response.response
    end
  end

end

modulo-3/sources/my_first_app/app/models/recipe.rb
require 'HTTParty'
class Recipe
  include HTTParty

  base_uri "http://food2fork.com/api"
  default_params key: "4c2e359020d616d50a5e070b6cfb0418"
  format :json
  #{"publisher"=>"Picky Palate", "f2f_url"=>"http://food2fork.com/view/484d98", "title"=>"Crock Pot Pesto Ranch Chicken Thighs", "source_url"=>"http://picky-palate.com/2012/09/20/pesto-ranch-crock-pot-chicken-thighs/", "recipe_id"=>"484d98", "image_url"=>"http://static.food2fork.com/CrockPotPestoRanchChickenThighs1text1300x248ca0b.jpg", "social_rank"=>99.99999999941502, "publisher_url"=>"http://picky-palate.com"}


  def self.for (keyword)
    get("/search", query: {q: keyword})["recipes"]
  end
end

modulo-3/sources/my_first_app/app/controllers/greeter_controller.rb
class GreeterController < ApplicationController

  def hello
    random_names = ["vanessa", "iván", "eduardo"]
    @name = random_names.sample
    @time = Time.now
    @times_displayed ||= 0
    @times_displayed += 1
  end

  #def goodbye
  #end

end

modulo-3/sources/my_first_app/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def search
    if(params[:text]=='nil')
      return nil
    end
    @text = params[:text] || 'chicken'
    @recipes = Recipe.for(@text)
  end
end

modulo-3/sources/my_first_app/app/controllers/translators_controller.rb
class TranslatorsController < ApplicationController
  def translate
    @google = GoogleTranslate.new("en", "es")
    @trans = params[:text] || "This is a really good party!"
    @response = @google.translate(@trans)
    @translations = @response['data']['translations'][0]['translatedText']
  end

  def detect
    @trans = "This is a really good party!"
    @detection = GoogleTranslate.detect(@trans)
    puts "#{@detection}"
  end

  def languages
    @target_language = params[:target_language] || "fr"
    @languages = GoogleTranslate.languages(@target_language)
    puts "Es posible traducir desde los siguientes idiomas: #{@list}"
  end
end

modulo-3/sources/my_first_app/app/helpers/greeter_helper.rb
module GreeterHelper
  def formatted_time(time)
    #Formateador AM/PM
    time.strftime("%I:%M:%p")
  end
end

modulo-3/sources/my_first_app/app/helpers/recipes_helper.rb
module RecipesHelper
end

modulo-3/sources/my_first_app/app/helpers/translators_helper.rb
module TranslatorsHelper
end

modulo-3/sources/my_first_app/app/views/greeter/goodbye.html.erb
<% random_names = ["vanessa", "iván", "eduardo"] %>
<h1>Goodbye, <%= random_names.sample %></h1>
<p>La hora es: <%= Time.now %></p>

modulo-3/sources/my_first_app/app/views/greeter/hello.html.erb
<h1>Greetings, <%= @name %></h1>
<p>La hora es: <%= formatted_time(@time) %></p>
<p>Esta página se ha mostrado en: 
  <%= @times_displayed %>  
  <%= @times_displayed == 1 ? "vez" : "veces"%>
</p>
<p> <%= link_to "Google", "http://www.google.com" %></p>
<p> <%= link_to "Goodbye", greeter_goodbye_path %></p>

  

modulo-3/sources/my_first_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

modulo-3/sources/my_first_app/app/views/recipes/search.html.erb
<h1>Buscando recetas con: <%= params[:text] %></h1>
  <table border="1">
    <tr>
      <th>Imagen</th>
      <th>Publisher</th>
      <th>Title</th>
    </tr>
    <% @recipes.each do |recipe| %>
      <tr class=<%= cycle('even', 'odd') %>>
        <td><%= image_tag(recipe["image_url"])%></td>
        <td><%= recipe['title'] %></td>
        <td><%= recipe['social_ra'] %></td>
      </tr>
    <% end %>
  </table>

modulo-3/sources/my_first_app/app/views/translators/detect.html.erb
<h1>Detected language !</h1>
<h2><%= @detection['data']['detections'][0][0]['language'] %></h2>

modulo-3/sources/my_first_app/app/views/translators/languages.html.erb
<h1>Idiomas en- <%= @target_language %></h1>

<table border="1">
  <tr>
    <th>Language</th>
    <th>Name</th>
  </tr>
  <% @languages['data']['languages'].each do |lang| %>
    <tr class=<%= cycle('even', 'odd') %>>
      <td><%= lang['name'] %></td>
      <td><%= lang['language'] %></td>
    </tr>
  <% end %>
</table>

modulo-3/sources/my_first_app/app/views/translators/translate.html.erb
<h1>Translated text!</h1>

<p><%= @translations%></p>